// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjVH-uJz4NDZgaDamsZEDBxjW0OWHDoB4',
    appId: '1:184837274645:web:992c9207dc3c7773f3a21c',
    messagingSenderId: '184837274645',
    projectId: 'kualitas-udara-95408',
    authDomain: 'kualitas-udara-95408.firebaseapp.com',
    storageBucket: 'kualitas-udara-95408.firebasestorage.app',
    measurementId: 'G-CZ33MQRRVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWf4j4JiCdmy0EMKw8uH5s0yyu1o_dU-o',
    appId: '1:184837274645:android:a8ef787010240bb1f3a21c',
    messagingSenderId: '184837274645',
    projectId: 'kualitas-udara-95408',
    storageBucket: 'kualitas-udara-95408.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjVH-uJz4NDZgaDamsZEDBxjW0OWHDoB4',
    appId: '1:184837274645:web:7ba840a858aa7cedf3a21c',
    messagingSenderId: '184837274645',
    projectId: 'kualitas-udara-95408',
    authDomain: 'kualitas-udara-95408.firebaseapp.com',
    storageBucket: 'kualitas-udara-95408.firebasestorage.app',
    measurementId: 'G-LQ5ZDFY4R2',
  );
}
